include: package:very_good_analysis/analysis_options.4.0.0.yaml
 
analyzer:
  errors:
    invalid_annotation_target: ignore
    todo: ignore
 
  exclude:
    - "test/.test_coverage.dart"
    - "lib/generated_plugin_registrant.dart"
    - "**.g.dart"
    - "*.freezed.dart"
    - "*.config.dart"
    - "packages"
 
linter:
  rules:
    always_put_control_body_on_new_line: true
    always_specify_types: true
    avoid_implementing_value_types: true
    depend_on_referenced_packages: true
    lines_longer_than_80_chars: false
    omit_local_variable_types: false
    prefer_foreach: true
    public_member_api_docs: false
    unsafe_html: true
    use_test_throws_matchers: true
    no_default_cases: false
    use_super_parameters: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_library_directive: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_checks: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    sort_constructors_first: false
    avoid_dynamic_calls: false